# Generated by Django 4.0.1 on 2022-04-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='c_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
