# Generated by Django 4.0.1 on 2022-05-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_register_c_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_desc',
            name='c_branch',
            field=models.CharField(choices=[('FE', 'Front-End'), ('BE', 'Back-End'), ('P', 'Programming')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='job_desc',
            name='c_course',
            field=models.CharField(choices=[('UG', 'Bachelors'), ('PG', 'Masters'), ('PHD', 'Philospher')], default='PG', max_length=5),
        ),
    ]
