# Generated by Django 4.0.1 on 2022-04-26 03:37

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_register_c_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=250, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254)),
                ('qualification', models.CharField(blank=True, max_length=250, null=True)),
                ('resume', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(default='', max_length=250)),
                ('s_name', models.CharField(blank=True, max_length=250)),
                ('s_password', models.CharField(blank=True, max_length=250)),
                ('s_confirm_password', models.CharField(blank=True, max_length=250)),
                ('dob', models.DateField()),
                ('emailid', models.EmailField(blank=True, max_length=254)),
                ('branch', models.CharField(choices=[('FE', 'Front-End'), ('BE', 'Back-End'), ('P', 'Programming')], default='CS', max_length=10)),
                ('course', models.CharField(choices=[('BTECH', 'bachelors'), ('MTECH', 'masters'), ('PHD', 'philospher')], default='BTECH', max_length=5)),
                ('s_verified', models.BooleanField(blank=True, default=False)),
                ('s_verification', models.IntegerField(blank=True, default=0)),
                ('contactno', models.CharField(blank=True, max_length=20)),
                ('resume', models.FileField(blank=True, upload_to=student.models.content_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_text', models.CharField(max_length=250, null=True)),
                ('old', models.BooleanField(default=True)),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.job_desc')),
                ('stdid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentdb')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('got_offer', models.CharField(default='No', max_length=250)),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.job_desc')),
                ('stdid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentdb')),
            ],
        ),
    ]
