# Generated by Django 4.0.1 on 2022-05-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='branch',
            field=models.CharField(choices=[('FE', 'Front-End'), ('BE', 'Back-End'), ('P', 'Programming')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='course',
            field=models.CharField(choices=[('UG', 'Bachelors'), ('PG', 'Masters'), ('PHD', 'Philospher')], default='PG', max_length=5),
        ),
    ]
